#!/bin/sh
# post-merge hook script to install Git hooks

echo "Running post-merge hook..."

# 調用安装 hooks 的 PowerShell 腳本
powershell.exe -ExecutionPolicy Bypass -File ./tool/install-hooks.ps1

# 輸出安裝完成的信息
echo "Hooks installed successfully."
